version: '3.0'
services:
  app:
    image: node:16
    user: "node"
    working_dir: /home/node/app/
    depends_on:
      - db
    environment:
      - NODE_ENV=development
    volumes:
      - ./app:/home/node/app
    ports:
      - "80:3000"
    command: "yarn start"
  mongo-express:
    image: mongo-express
    restart: always
    depends_on:
      - db
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
  db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017