name: Api

on:
  push:
    branches:
      - main
    paths:
      - api/**
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./api
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '18'
        cache: 'yarn'
        cache-dependency-path: api/yarn.lock
    - name: Install node dependencies
      run: yarn install --prefer-offline
    - name: Env configuration
      run: |
        mv .env.prod .env
        rm .env.example
        echo -e '\nDB_PASS="${{ secrets.DB_PASS }}"' >> .env
    - name: Compile assets
      run: yarn build
    - name: Deploy api
      uses: burnett01/rsync-deployments@5.1
      with:
        switches: -avzr
        path: api/dist/
        remote_path: ${{ secrets.DEPLOY_API_PATH }}
        remote_host: ${{ secrets.DEPLOY_HOST }}
        remote_port: ${{ secrets.DEPLOY_PORT }}
        remote_user: ${{ secrets.DEPLOY_USER }}
        remote_key: ${{ secrets.DEPLOY_KEY }}
    - name: Deploy node_modules
      uses: burnett01/rsync-deployments@5.1
      with:
        switches: -avzr
        path: api/node_modules
        remote_path: ${{ secrets.DEPLOY_API_PATH }}
        remote_host: ${{ secrets.DEPLOY_HOST }}
        remote_port: ${{ secrets.DEPLOY_PORT }}
        remote_user: ${{ secrets.DEPLOY_USER }}
        remote_key: ${{ secrets.DEPLOY_KEY }}
    - name: Deploy .env
      uses: burnett01/rsync-deployments@5.1
      with:
        switches: -avzr
        path: api/.env
        remote_path: ${{ secrets.DEPLOY_API_PATH }}
        remote_host: ${{ secrets.DEPLOY_HOST }}
        remote_port: ${{ secrets.DEPLOY_PORT }}
        remote_user: ${{ secrets.DEPLOY_USER }}
        remote_key: ${{ secrets.DEPLOY_KEY }}