name: Build and Deploy

on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app
    steps:
    - uses: actions/setup-node@v2
      with:
        node-version: '18'
    - name: Install node dependencies
      run: yarn install --prefer-offline
    - name: Env configuration
      run: mv .env.prod .env
    - name: Compile assets
      run: yarn build
    - name: Deploy
      uses: burnett01/rsync-deployments@5.1
      with:
        switches: -avzr
        path: app/
        remote_path: ${{ secrets.DEPLOY_PATH }}
        remote_host: ${{ secrets.DEPLOY_HOST }}
        remote_port: ${{ secrets.DEPLOY_PORT }}
        remote_user: ${{ secrets.DEPLOY_USER }}
        remote_key: ${{ secrets.DEPLOY_KEY }}